OfficeDev/microsoft-teams-app-schema

- MicrosoftTeams.schema.json
Supports the configuration URL for the new inline connector experience
> Added support for configurationUrl

- README.md
We can wait to publish based on the /en-us/ answer from the Office folks or we can update later.
> Update readme with information on where to find distribution files

- MicrosoftTeams.schema.json
This schema node is not yet available in the Teams client
> Remove webApplicationInfo

- README.md
Need to do it in the branch I created too!
> Removed reference to vNext and added DevPreview branch

- MicrosoftTeams.schema.json
preview/DevPreview contains this already. 
Merge this to master before release to R4.
> [merge to master for R4] Changes for calling bots

- MicrosoftTeams.schema.json
This change adds the webApplicationInfo section (with id and resource fields) to the app manifest. This section will be used to enable AAD token acquisition and pre-fetching for Teams apps.
> Merge SSO changes into master for v1.4 release

- README.md
Added a reference to https://github.com/Microsoft/json-schemas
> Add reference to repo for Microsoft schemas

- MicrosoftTeams.schema.json
Reverts OfficeDev/microsoft-teams-app-schema#25
> Revert "adding supported platforms field, tiny name and selected outline icon for tabs support on mobile"

- MicrosoftTeams.schema.json
Reverts OfficeDev/microsoft-teams-app-schema#40
> Revert "Update MicrosoftTeams.schema.json"

- MicrosoftTeams.schema.json
Add description for webapp info. Change permissions for device permissions.
> Description changes for webapp info and device permissions

- MicrosoftTeams.schema.json
This change will need to be reverted when the MT goes out next
> lowercase commandbox

- MicrosoftTeams.schema.json
This option isn't that widely supported yet.
> Remove negative look behind for 1.5 schema

- MicrosoftTeams.schema.json
Adding show Loading indicator to dev preview of app schema.
> adding show Loading indicator to dev preview

- MicrosoftTeams.schema.json
Adding isFullscreen property to allow full-screen capability for LOB apps
> Added isFullscreen property to allow full-screen capability for LOB apps

- MicrosoftTeams.schema.json
Added isFullscreen property to allow full-screen capability for LOB apps
> Added isFullscreen property to allow full-screen capability for LOB apps 

- MicrosoftTeams.schema.json
Sidhaw/schema updates meeting context for static and configurable Tabs
> Sidhaw/schema updates meeting context for static and configurable Tabs

- MicrosoftTeams.schema.json
Add optional botId property to staticTabs to enable Adaptive Card Tabs
> add optional botId property to staticTabs

- MicrosoftTeams.schema.json
`[Link to spec](https://microsoft.sharepoint.com/:w:/t/ExtensibilityandFundamentals/ETV4lkQY3ldMjGOR8zM-bkYBV7lkiLeOhyYG5MlhErggaQ?e=P87sQe)`
> removing required field

- MicrosoftTeams.schema.json
Updating the order of enums to match what is currently in the MT code.
> updating order of scopes and capabilities

- MicrosoftTeams.schema.json
Made changes in manifest to support platform flag in static tabs and configurable tabs
> [Teams Mobile] Platform flag added for static and configurable tabs

- MicrosoftTeams.schema.json
Adding array of enums to support configurable app properties
> Add configurableProperties to support app customization

- MicrosoftTeams.schema.json
Add Together mode MeetingExtensionDefinition section into public manifest
> Add MeetingExtensionDefinition

- MicrosoftTeams.schema.json
Added subscriptionOffer.
MT middle tier change is completed here:
https://domoreexp.visualstudio.com/DefaultCollection/Teamspace/_git/Teamspace-MiddleTier/pullrequest/308453?path=%2FSource%2FBackendServices%2FBackendServices%2FSettingsStore%2FModels%2FApps%2FAppDefinitionItem.cs
Settings Store PR is at:
https://domoreexp.visualstudio.com/Teamspace/_git/SkypeTeams-SettingsStore/pullrequest/310100?path=%2FSource%2FSettingsStore%2FSettingsStore.WebAppService%2FApp_Data%2Fteams_apps_definitionv2.json
> Update MicrosoftTeams.schema.json with subscriptionOffer

- MicrosoftTeams.schema.json
Add Authorization section and remove ApplicationPermissions from WebApplicationInfo
> Update schema for app authorization section

- MicrosoftTeams.schema.json
Reverts OfficeDev/microsoft-teams-app-schema#124
> Revert "Update schema for app authorization section"

- MicrosoftTeams.schema.json
Details:
Add graphConnector section to allow applications to specify graph connector support.
> Update schema with graph connector information.

- MicrosoftTeams.Localization.schema.json
- MicrosoftTeams.ResponseRenderingTemplate.schema.json
- MicrosoftTeams.schema.json
> Update schema to v17

- MicrosoftTeams.schema.json
> Hotfix For GA schema
